FROM localhost/archlinux
VOLUME /store
VOLUME /stash
COPY etc/skel /etc/
RUN mkdir /usr/share/lisp
RUN mkdir /usr/local/share/lisp
RUN --network=host pacman -Syu base-devel gnupg openssh mercurial git sqlite tmux btrfs-progs liburing wireguard-tools cargo clang llvm tree-sitter --noconfirm
WORKDIR /usr/local/src
RUN hg clone https://vc.compiler.company/comp/infra
RUN hg clone https://vc.compiler.company/comp/demo
RUN hg clone https://vc.compiler.company/comp/org
RUN hg clone https://vc.compiler.company/comp/core
WORKDIR infra
RUN make build
ENV CARGO_HOME="/usr/local/share/cargo"
ENV RUSTUP_HOME="/usr/local/share/rustup"
RUN make rustup-install
ENV PATH="$PATH:/usr/local/share/cargo/bin"
RUN rustup update && rustup default nightly
RUN sh scripts/install-emacs-pack.sh
RUN sh scripts/install-sbcl-pack.sh
RUN sh scripts/install-rocksdb-pack.sh
RUN make quicklisp-install
RUN make tree-sitter-langs-install
COPY etc/sbclrc /etc/sbclrc
RUN make core-install
RUN make clean
EXPOSE 8080
WORKDIR /