FROM localhost/ci-worker
RUN adduser -D operator
RUN apk add --no-cache tree-sitter-dev autoconf texinfo libgccjit-dev zlib-dev gnutls-dev sysprof gpg bash json-c-dev ncurses-dev
WORKDIR /usr/local/src/core
RUN hg pull -u
WORKDIR /infra
RUN hg pull -u