FROM localhost/alpine
VOLUME /store
VOLUME /stash
COPY etc/skel /etc/
RUN adduser -D worker
RUN apk add build-base zstd-dev sbcl curl make git linux-headers cargo openssl-dev perl llvm pkgconf clang m4
RUN mkdir /usr/share/lisp
RUN mkdir /usr/local/share/lisp
WORKDIR /usr/local/src
RUN hg clone https://vc.compiler.company/comp/infra
RUN hg clone https://vc.compiler.company/comp/core
WORKDIR infra
RUN make worker -j4
RUN make clean
COPY etc/sbclrc /etc/sbclrc