FROM localhost/alpine:latest
# VOLUME /opt/store
# VOLUME /opt/stash
ADD etc/skel/* /etc/skel/
ARG ID=908
ARG WORKER=worker
ARG WORKER_HOME=/home/${WORKER}
RUN apk add build-base zstd-dev curl make git linux-headers openssl-dev pkgconf clang m4 tree-sitter
RUN mkdir /usr/share/lisp
RUN mkdir /usr/local/share/lisp
WORKDIR /usr/local/src
RUN hg clone https://vc.compiler.company/comp/infra
RUN hg clone https://vc.compiler.company/comp/core
WORKDIR infra
ENV CARGO_HOME="/usr/local/share/cargo"
ENV RUSTUP_HOME="/usr/local/share/rustup"
RUN make build rustup-install tree-sitter-langs-install
ENV PATH="$PATH:/usr/local/share/cargo/bin"
RUN rustup update 
#RUN rustup default nightly # disabled due to issue with zellij build
ADD etc/sbclrc /etc/sbclrc
RUN cd .. && rm -rf infra core
RUN adduser -D -u ${ID} -k /etc/skel ${WORKER}
USER ${WORKER}
WORKDIR ${WORKER_HOME}
ENV WORKER=${WORKER}
ENV WORKER_ID=${ID}
ENV WORKER_HOME=${WORKER_HOME}
ENTRYPOINT ["sh"]