FROM alpine-base AS ci-worker
VOLUME /store
VOLUME /stash
COPY etc/skel /etc/
RUN adduser -D worker
RUN apk add build-base zstd-dev sbcl curl make git linux-headers cargo openssl-dev perl llvm clang pkgconf
RUN mkdir /usr/share/lisp
RUN mkdir /usr/local/share/lisp
RUN hg clone https://vc.compiler.company/comp/infra
WORKDIR /usr/local/src
RUN hg clone https://vc.compiler.company/comp/core
WORKDIR /infra
RUN make worker -j4
RUN scripts/install-cargo-tools.sh
RUN make clean
COPY etc/sbclrc /etc/sbclrc