FROM infra/archlinux
VOLUME /store
VOLUME /stash
# custom
ARG DEV=dev
ARG DEV_HOME=/home/${DEV}
ARG ID=808
# stage0
RUN mkdir -p /usr/share/lisp /usr/local/share/lisp
WORKDIR /usr/local/src
RUN hg clone https://vc.compiler.company/comp/infra
RUN hg clone https://vc.compiler.company/comp/core
WORKDIR infra
RUN make build
ENV CARGO_HOME="/usr/local/share/cargo"
ENV RUSTUP_HOME="/usr/local/share/rustup"
# stage1
RUN make rustup-install
ENV PATH="$PATH:/usr/local/share/cargo/bin"
RUN rustup update && rustup default nightly
RUN sh scripts/install-nushell-pack.sh
RUN sh scripts/install-emacs-pack.sh
RUN sh scripts/install-sbcl-pack.sh
RUN sh scripts/install-rocksdb-pack.sh
RUN sh scripts/install-cargo-tools.sh
RUN make quicklisp-install
RUN make tree-sitter-langs-install
ADD etc/sbclrc /etc/sbclrc
COPY etc/skel/ /etc/skel/
ADD etc/shells /etc/
RUN useradd --system -s /usr/local/bin/nu -u ${ID} -k /etc/skel -m ${DEV}
RUN groupadd -g 128 engineer -U ${DEV}
RUN groupadd -g 256 operator -U ${DEV}
RUN chown -R ${DEV}:engineer /usr/local/share/
RUN chown -R ${DEV}:engineer /usr/local/src/
RUN chown -R ${DEV}:engineer /usr/local/bin/
RUN chown -R ${DEV}:engineer /usr/local/etc/
RUN chown -R ${DEV}:engineer /usr/local/man/
RUN make core-install
WORKDIR /usr/local/src
RUN cp -rf core/lisp /usr/local/share/lisp/core
RUN rm -rf ./*
USER ${DEV}
WORKDIR ${DEV_HOME}
RUN hg clone https://vc.compiler.company/comp/infra
ENV DEV=${DEV}
ENV DEV_ID=${ID}
ENTRYPOINT ["/usr/local/bin/nu"]
CMD ["-i"]
