FROM localhost/alpine:latest
# VOLUME /opt/store
# VOLUME /opt/stash
# ADD etc/skel/* /etc/skel/
ARG ID=908
ARG WORKER=worker
ARG WORKER_HOME=/home/${WORKER}
RUN apk add build-base zstd-dev curl make git linux-headers openssl-dev pkgconf clang m4 tree-sitter
RUN mkdir /usr/share/lisp
RUN mkdir /usr/local/share/lisp
WORKDIR /usr/local/src
WORKDIR infra
RUN mkdir .stash
RUN sh scripts/get-sk.sh
ENV CARGO_HOME="/usr/local/share/cargo"
ENV RUSTUP_HOME="/usr/local/share/rustup"
RUN .stash/sk make rustup tree-sitter-langs
ENV PATH="$PATH:/usr/local/share/cargo/bin"
RUN rustup update 
RUN rustup default nightly
RUN cd .. && rm -rf infra core
RUN adduser -D -u ${ID} -k /etc/skel ${WORKER}
USER ${WORKER}
WORKDIR ${WORKER_HOME}
ENV WORKER=${WORKER}
ENV WORKER_ID=${ID}
ENV WORKER_HOME=${WORKER_HOME}
ENTRYPOINT ["sh"]